### ISSUE TITLE
Have to load at least one core RBF before it will unlock the keyboard / OSD...

### ISSUE THREAD

**Issue by ElectronAsh** [MiSTer-devel/Menu_MiSTer#1]
Not a major bug, but when you first use the latest SD Formatter to start using the new updater script, the menu won't unlock the OSD, so you can't get to the Scripts function.

At least one core RBF has to be copied onto the SD card (root?) first.

The scripting stuff is awesome, btw. ;)

**Comment by ElectronAsh** [comment]
Oh, I think what is happening with some scripts is that when you allow it to auto-reset MiSTer, it's possibly leaving osd_enable set, so it thinks the OSD is still open when the core reloads?

So, when you go to use the keyboard (say in the ao486 core), it's trying to use the OSD options in the background.

This was with the latest MiSTer and menu.rbf, and using the updater script.

**Comment by sorgelig** [comment]
Script may brake the normal work. It's not the normal MiSTer operation.

**Comment by sorgelig** [comment]
it's fixed.
