### ISSUE TITLE
F1 for Background Switching Not Working

### ISSUE THREAD

**Issue by EvanGrill** [MiSTer-devel/Menu_MiSTer#10]
I'm not sure which core release removed it, but it appears that pressing F1 to change core backgrounds has been removed.  Is it possible to change backgrounds any other way?

**Comment by sorgelig** [comment]
It's not removed. It's still there.
If you use VGA output then it's possible you use native video output where backgrounds aren't supported.

**Comment by EvanGrill** [comment]
So if I use VGA out AND HDMI out I can't change the background? When I hit F1, literally nothing happens.

The reason I bring this up is that I realized last night that when attempting to capture the default static background OBS's encoder dies and drops frames like crazy.

**Comment by sorgelig** [comment]
You need to choose either HDMI or VGA (with direct video enabled). If you want to use both then VGA output won't have background.

**Comment by EvanGrill** [comment]
I apologize if I'm not understanding this correctly. My personal setup (and I'm sure others are using this as well) is IO Board RGBS to a CRT and HDMI Out (1080p60, not direct video) to the capture card.  Pressing F1 on the keyboard does literally nothing.  No menu, no indication that the feature isn't supported, no response whatsoever.  

If this is as intended is it possible to remove the "static" background in favor of something that isn't animated, or at least doesn't destroy video encoders?

**Comment by sorgelig** [comment]
MiSTer NEVER intended to be a dual output. Basically you misuse the MiSTer. There are restrictions when dual output won't work with all features or even misbehave. 
Since you capture from HDMI where backgrounds are always available, F1 should be able to switch between noise/gradients/picture - this is what you want. However on CRT you will always will see only noise output. So to see the effect of F1, you need to look for it on capture card, not on your CRT.

**Comment by EvanGrill** [comment]
I figured out the issue.  "fb_terminal=1" needs to be set in the MiSTer.ini file in order for background switching to work.  This doesn't appear in any documentation that I've seen.

@sorgelig I really appreciate the support and I want to thank you again for your work on such an amazing project.
