### ISSUE TITLE
No image on CRT TV using direct_video

### ISSUE THREAD

**Issue by el-goe** [MiSTer-devel/Menu_MiSTer#11]
No image is displayed on a standard 15khz CRT tv when setting direct_video = 1. When launching a 15khz compatible core like genesis/snes/etc it works fine.

Also in the menu, if I hold Reset button the menu is visible but then of course it resets after letting it go.

**Comment by sorgelig** [comment]
Most likely it' not a bug but some misconfiguration. 
Please use forum for discussions. Not github.

**Comment by el-goe** [comment]
Thanks.
