### ISSUE TITLE
Long MRA titles not displayed correctly in “Cores” list

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Menu_MiSTer#13]
Using the latest menu core,ong MRA titles word-wrap when highlighted, but then the first line also starts horizontally scrolling, which looks buggy.  See attached photo.
![5AA1D8A4-D511-44F3-9AA1-035BC521259A](https://user-images.githubusercontent.com/24398884/82833846-1f7e7e80-9e74-11ea-960d-8d32b906e12c.jpeg)

**Comment by sorgelig** [comment]
it's not a bug, it's a feature.
add browse_expand=0 into ini file if you don't like it.

**Comment by c0d3h4x0r** [comment]
That fixed it.  Thanks!
