### ISSUE TITLE
Menu Back while browsing zip files causes MiSTer_alt_3.ini to load

### ISSUE THREAD

**Issue by kousaka** [MiSTer-devel/Menu_MiSTer#16]
I have 3 alt ini's defined. I've tested this in multiple console cores and when I load a game and a navigate into a zip file if I hit menu back the config switches to MiSTer_alt_3.ini from the main ini. I'm using a DS4 and have O mapped to accept and X mapped to back.

I can go into the menu and switch it back manually.

If I just delete all the alt ini files it's fine although there's a small pause when I back manually.

I know that back button + down switches to alt 3 ini so I suspect pressing back while in a zip file is triggering back button + down somehow.

**Comment by sorgelig** [comment]
Hmm, i cannot reproduce this..
May be your DS4 has loose analog sticks and then it generates high value of "analog down" and it triggers the config switch?

**Comment by sorgelig** [comment]
Anyway, i will limit config switch to specific pages only to minimize such behavior

**Comment by kousaka** [comment]
Swapped out DS4 and the problem seems to be resolved.

Tested the DS4 some more and it happened only when browsing very large zip files.

**Comment by kousaka** [comment]
But I think your right. Occasionally I will get an extra directional down while navigating using the DS4.
