### ISSUE TITLE
Refresh Rate Display

### ISSUE THREAD

**Issue by mjj03301977** [MiSTer-devel/Menu_MiSTer#19]
Would it be possible to show the refresh rate with a few more decimal places? So instead of showing 59.x, show 59.xyz.

**Comment by birdybro** [comment]
This comes from main's side of things and doesn't involve the Menu core. If you want to know the refresh rate in more detail just open a console connection and load the target core or load a rom which changes the refresh rate, the console output displays what it is currently set to at that time.

This can be closed.
