### ISSUE TITLE
1920x1080@60 is broken in Release 20190119 re-up

### ISSUE THREAD

**Issue by dukesilverfan** [MiSTer-devel/Menu_MiSTer#2]
1080@60 has worked fine in the past, but with Release 20190119 re-up, the screen just scrolls and glitches out so you can't do anything. By using SSH/FTP to access the system and change to 720@60, the screen is fine. I was't sure whether to create this issue in Menu_MiSTer or MiSTer Main, but it is a new issue as of today.

**Comment by sorgelig** [comment]
there was glitchy version of Menu core in original 20190119 release. Make sure you use refreshed one.

**Comment by dukesilverfan** [comment]
I updated via the update script when this happened. I will try doing it manually and report back, closing if it fixes it.

**Comment by dukesilverfan** [comment]
This was fixed by manually updating the menu via the sd card. It appears that the updater script was failing to update this, maybe it didn't recognize the file as changed. Either way, a manual update fixed it.
