### ISSUE TITLE
Menu cursor continually scrolling when RGB connected

### ISSUE THREAD

**Issue by dspiteri** [MiSTer-devel/Menu_MiSTer#22]
Menu now scrolls the cursor down continually when an RGB display is connected to the IO Board. This stops after a core is selected, only happens when menu.rbf is active. Verified with all other peripherals disconnected and doesn't happen when on HDMI only.

This is a recent change after I updated on the weekend to Mister V21112. Menu didn't update but I noticed a change in behaviour that was OK before.

**Comment by sorgelig** [comment]
i don't see any connection between display type and cursor scrolling.
Try to plug your keyboard/gamepad in other port of USB hub.

**Comment by dspiteri** [comment]
Hi Sorgelig, I tested with no USB or other peripherals connected, only happens when RGB is connected. Maybe related to the recent Linux update? Maybe it's a hardware issue on my IO board, just wondering if anyone else has seen. I'll take it to forums if you prefer.

**Comment by sorgelig** [comment]
Does it happen when some input device is connected or you didn't connect ANY USB devices? What USB hub you use?

**Comment by dspiteri** [comment]
It happens with no USB deviced connected at all, I even disconnected the USB bridge to the 7port board. Only happens when RGB cable is connected and only after booting up, no problem after a core is selected only when menu.rbf is sitting there.

**Comment by sorgelig** [comment]
I never heard about such problem. May be something wrong with your MiSTer either HW or SW setup. If nothing is connected then cursor should not move..

**Comment by dspiteri** [comment]
I just updated file MiSTer from Distribution_MiSTer and the issue stopped. Thanks for your feedback and all your good work sorgelig.

**Comment by diabolicfutility** [comment]
I also had this issue. For me the cause was accidentally choosing the DB9 MiSTer fork in the update_all script rather than the official MiSTer distribution.
