### ISSUE TITLE
Fighting Scrolling Text Priority

### ISSUE THREAD

**Issue by tonurics** [MiSTer-devel/Menu_MiSTer#23]
https://user-images.githubusercontent.com/983921/156935110-2d2361a5-0aa9-4f07-a359-f0559e7f4739.mp4

Two scrolling text elements will fight each other when being drawn.

**Comment by birdybro** [comment]
This issue can probably be closed as it's applicable to Main_MiSTer instead of Menu_MiSTer.

**Comment by sorgelig** [comment]
and this is already fixed in repository. Will be included in next release.
