### ISSUE TITLE
Issue with menu and bluetooth keyboard simulating remote (works in terminal)

### ISSUE THREAD

**Issue by werpu** [MiSTer-devel/Menu_MiSTer#32]
Hello, I have a bluteooth Remote which simulates a generic bluetooth keyboard. I have the problem that pairing works fine, but after that, I cannot use the cursor keys which simulate keyboard cursor keys to move around in the menu, other keys like escape seem to be recognized just fine, just the cursor keys make problem. To make matters worse, if I open a bash on mistler, it works like expected I can move the cursor around in the command line. So I assume something fishy is going on with the menu navigation code.
(I will post the logged btmon codes further down)

Second bug, I tried to remap the cursor keys on a normal keyboard to WSAD, the result was that neither worked in the menu, so key remapping the up down left and arrow keys is not an option either atm!

Here are the btmon codes logged from my remote
up:
> ACL Data RX: Handle 16 flags 0x02 dlen 15               #96 [hci0] 272.787667
      ATT: Handle Value Notification (0x1b) len 10
        Handle: 0x001f
          Data: 0000520000000000
> ACL Data RX: Handle 16 flags 0x02 dlen 15               #97 [hci0] 272.788852
      ATT: Handle Value Notification (0x1b) len 10
        Handle: 0x001f
          Data: 0000000000000000

Down:
> ACL Data RX: Handle 16 flags 0x02 dlen 15               #98 [hci0] 289.213392
      ATT: Handle Value Notification (0x1b) len 10
        Handle: 0x001f
          Data: 0000510000000000
> ACL Data RX: Handle 16 flags 0x02 dlen 15               #99 [hci0] 289.214566
      ATT: Handle Value Notification (0x1b) len 10
        Handle: 0x001f
          Data: 0000000000000000
       
Left:
 ACL Data RX: Handle 16 flags 0x02 dlen 15              #100 [hci0] 311.849967
      ATT: Handle Value Notification (0x1b) len 10
        Handle: 0x001f
          Data: 0000500000000000
> ACL Data RX: Handle 16 flags 0x02 dlen 15              #101 [hci0] 311.850000
      ATT: Handle Value Notification (0x1b) len 10
        Handle: 0x001f
          Data: 0000000000000000
Right:
> ACL Data RX: Handle 16 flags 0x02 dlen 15              #102 [hci0] 334.800048
      ATT: Handle Value Notification (0x1b) len 10
        Handle: 0x001f
          Data: 00004f0000000000
> ACL Data RX: Handle 16 flags 0x02 dlen 15              #103 [hci0] 334.801181
      ATT: Handle Value Notification (0x1b) len 10
        Handle: 0x001f
          Data: 0000000000000000

showkey -a in a bash gives me the exactly same results on a physical usb keyboard and on the simulated one from the remote
aka 
27 0033 0x1b
91 0133 0x5b
65 0101 0x41

My guess is that there might be some weird timing code which prevents the remotes arrow keys to be properly recognized (maybe some debounce code which waits for a certain lenght of time or so)

I tried with two different bluetooth dongles, both same result. I cannot try with a bt keyboard since I have none!

**Comment by sorgelig** [comment]
Enable debug mode in MiSTer.ini (debug=1)
Then connect to MiSTer through USB console port to, load menu core and check which buttons are reported there when you press up/down buttons.

here down/up codes from normal keyboard:
```
046d:4024:00 P0 Input event: type=EV_KEY, code=108(0x6c), value=0
PS2 code(break)(ext) for core: 114(0x72)
046d:4024:00 P0 Input event: type=EV_KEY, code=103(0x67), value=1
PS2 code(make)(ext) for core: 117(0x75)
```

**Comment by werpu** [comment]
Mhhh I do not have the technical means (I probably have to get a uart to usb connector from what I have read), is there any way to debug this out with a standard ssh connection?

**Comment by werpu** [comment]
Just adding some information. I tried another core (pc) and there the up and down via bluetooth works fine. So the problem lies definitely within the main menu core which does not react to the bt ups and downs, everything else does!

**Comment by sorgelig** [comment]
It's hard to understand what causes the problem. Does it generate make/break codes instantly when you press the key, or it generates break code when you release the key?

**Comment by werpu** [comment]
It generates both codes when I press the key as far as I remember not going from 1/0 when I release it!

**Comment by werpu** [comment]
I ran a timing test. The remote indeed has a very low latency between down and up. My tests show a latency of<1ms or 1ms. While a manual keypress on a really flat keyboard performed really fast showed me on the same test setup a latency of 20-40ms. So the latency of naturaly keypresses is 20-40x higher than what the remote sends into the mister!
I will contact the remote guys, and see what they think of it!

**Comment by werpu** [comment]
I would leave this issue for now, I think this must be sorted out on the remote side, in fact I talked to one of the devs there and he said long press is not yet implemented properly. So I guess the bug is on the remotes side since polling is a viable way to get the keypresses on many games!
Sorry for opening a bug here, at least I came down to the core of the problem more or less!

**Comment by werpu** [comment]
not an issue with the menu for now
