### ISSUE TITLE
Feature request: Vertical screen support

### ISSUE THREAD

**Issue by eskwadrat** [MiSTer-devel/Menu_MiSTer#8]
For all those including myself who built the MISTer nano into arcade cabinet w/vertically positioned monitor, it would be a big improvement to have MISTer menu displayed vertically to navigate games and cores more easily. 
With that, an option to select and save vertically displayed menu in the nano board would be essential, so everytime it boots, the MISTer menu follow this setting w/o need for user selection. 

________________
MISTer patreon

**Comment by sorgelig** [comment]
implemented.
Although this option is clearly only for arcades. It will be hard to use non-vertical cores in such cabinet.

**Comment by Sinaloagold** [comment]
If this feature was implemented, how can we turn it on? Thanks

**Comment by sorgelig** [comment]
osd_rotate=1
in ini file.
