### ISSUE TITLE
Release 20190907 introduces graphical glitches

### ISSUE THREAD

**Issue by apolkosnik** [MiSTer-devel/Menu_MiSTer#9]
Release 20190907 introduces graphical glitches. The background gets corrupted, minimig appears to have a black screen and if anything shows the colors are off. After rolling back menu to the previous version, it works as expected.

**Comment by sorgelig** [comment]
show the photo of corrupted background.
For me it sounds like very well known DDR3 bridge glitch which is present from the day 1. Cold reset or power cycle fixes the problem.

**Comment by zomgugoff** [comment]
I am having graphical issues over HDMI with the menu on this build. The screen blanks randomly and there are some black lines appearing at the top of the screen. The dropouts are so bad that sometimes only a frame is shown every minute. VGA and other cores appear to be unaffected.

**Comment by sorgelig** [comment]
try this version:
[menu.zip](https://github.com/MiSTer-devel/Menu_MiSTer/files/3586516/menu.zip)

**Comment by zomgugoff** [comment]
Well... It did stop blanking, but backgrounds have some artifacting. I have attached a photo.
![0907190414](https://user-images.githubusercontent.com/40047378/64474177-16068800-d126-11e9-90b0-17bb4598d87e.jpg)

**Comment by sorgelig** [comment]
How about this version:
[menu2.zip](https://github.com/MiSTer-devel/Menu_MiSTer/files/3586565/menu2.zip)

**Comment by zomgugoff** [comment]
There's a little flickering on the very right side of the screen, but that was present on the 20190824 build. I think you got it.

**Comment by sorgelig** [comment]
so it's not worse than 20190824?

**Comment by zomgugoff** [comment]
No, it looks to be the same.

**Comment by sorgelig** [comment]
i close this issue.
Open new one if latest release has the same problem.
